#!/usr/bin/env bash

echo -e "\nInstalling Essential Tools\n"

PKGS=(
  'kitty'                   # terminal
  'exa'                     # ls
  'bat'                     # cat
  'htop'                    # task manager
  'neofetch'                # system info
  'systemd-swap'            # swap
  'openssh'                 # ssh
  'xdg-user-dirs'

  # file system and partition tools
  'exfat-utils'
  'ntfs-3g'
  'gparted'
)

TOOLS=(
  # archiving tools
  'lrzip'
  'lrzop'
  'p7zip'
  'unarchiver'
  'unrar'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm --needed
done
for TOOL in "${TOOLS[@]}"; do
    echo "INSTALLING: ${TOOL}"
    sudo pacman -S "$TOOL" --noconfirm --needed --asdeps
done

xdg-user-dirs-update
sudo systemctl enable systemd-swap

echo -e "\nDone!\n"
