#!/usr/bin/env bash

echo -e "\nInstalling yay\n"

git clone https://aur.archlinux.org/yay.git ~/yay
cd ~/yay
makepkg -si

echo -e "\nInstalling Essential Tools\n"

PKGS=(
  'kitty'                   # terminal
  'exa'                     # ls
  'bat'                     # cat
  'htop'                    # task manager
  'neofetch'                # system info
  'openssh'                 # ssh
  'curl'
  'xclip'
  'xdg-user-dirs'
  'base-devel'
  'reflector'

  # file system and partition tools
  'exfat-utils'
  'ntfs-3g'
  'gparted'

  # archiving tools
  'lrzip'
  'lrzop'
  'p7zip'
  'unarchiver'
  'unrar'
  'unzip'
  
  # php requirements
  'icu'
  'postgresql-libs'
  'zlib'
  'oniguruma'
  're2c'
  'gd'
  'libzip'
  'imagemagick'
  'djvulibre'
  'ghostscript'
  'imagemagick-doc'
  'libheif'
  'libraw'
  'librsvg'
  'libwebp'
  'libwmf'
  'libxml2'
  'ocl-icd'
  'openexr'
  'openjpeg2'
  'pango'
  'libxslt'

  'ttf-font'
)

for PKG in "${PKGS[@]}"; do
  yay -S "$PKG" --noconfirm --needed
done

xdg-user-dirs-update

curl -Lk https://gitlab.com/andres-dc/dots/-/raw/main/.restore | /bin/bash

echo -e "\nDONE!\n"
