#!/usr/bin/env bash

echo -e "\nInstalling Browsers\n"

PKGS=(
  'min'
  'firefox'
  'vivaldi'
  'vivaldi-ffmpeg-codecs'
)

for PKG in "${PKGS[@]}"; do
  sudo pacman -S "$PKG" --noconfirm --needed
done

echo -e "\nDone!\n"
