#!/usr/bin/env bash

echo -e "\nInstalling fonts\n"

PKGS=(
  # fonts
  'noto-fonts-emoji'
  'otf-fira-mono'
  'ttf-anonymous-pro'
  'ttf-fantasque-sans-mono'
  'ttf-fira-code'
  'ttf-fira-mono'
  'ttf-inconsolata'
  'ttf-linux-libertine'
  'ttf-roboto'
  'ttf-ubuntu-font-family'
  'xorg-fonts'

  # ttf-fonts
  'gnu-free-fonts'
  'noto-fonts'
  'ttf-bitstream-vera'
  'ttf-croscore'
  'ttf-dejavu'
  'ttf-droid'
  'ttf-font-awesome'
  'ttf-ibm-plex'
  'ttf-liberation'
  'ttf-iosevka-nerd'
  'ttf-terminus-nerd'

  'ttf-nerd-fonts-victor-mono'
  'nerd-fonts-dejavu-complete'
  'ttf-ms-fonts'
)

for PKG in "${PKGS[@]}"; do
  yay -S "$PKG" --noconfirm --needed
done

echo -e "\nDONE!\n"
