#!/usr/bin/env bash

echo -e "\nInstalling AUR packages\n"

PKGS=(
  'slack-desktop'
  'insomnia'
  'skypeforlinux-stable-bin'
)

for PKG in "${PKGS[@]}"; do
  yay -Sua "$PKG" --noconfirm --needed
done

echo -e "\nDONE!\n"
