#!/usr/bin/env bash

echo -e "\nInstalling AUR packages\n"

git clone https://aur.archlinux.org/yay.git ~/yay
cd ~/yay
makepkg -si

PKGS=(
  'slack-desktop'
  'insomnia'
  'skypeforlinux-stable-bin'
)

for PKG in "${PKGS[@]}"; do
  yay -S "$PKG" --noconfirm --needed
done

echo -e "\nDone!\n"
