#!/usr/bin/env bash

echo -e "\nInstalling extras\n"

PKGS=(
  'bitwarden'
  'keepassxc'
  'discord'
)

AURPKGS=(
  'slack-desktop'
  'zoom'
  'protonvpn'
  'megasync'
  'dolphin-megasync'
)

for PKG in "${PKGS[@]}"; do
  sudo pacman -S "$PKG" --noconfirm --needed
done

for AURPKG in "${AURPKGS[@]}"; do
  yay -Sua "$AURPKG" --noconfirm --needed
done

echo -e "\nDONE!\n"
