#!/usr/bin/env bash

echo -e "\nInstalling extras\n"

PKGS=(
  'bitwarden'
  'discord'

  'slack-desktop'
  'zoom'
  'protonvpn-cli'
  'megasync'
  'dolphin-megasync'
)

for PKG in "${PKGS[@]}"; do
  yay -S "$PKG" --noconfirm --needed
done

echo -e "\nDONE!\n"
