#!/usr/bin/env bash

echo -e "\nInstalling devtools\n"

PKGS=(
  'postgresql'
  'mariadb'
  'mysql-workbench'
  'dbeaver'
)

AURPKGS=(
  'visual-studio-code-bin'
)

for PKG in "${PKGS[@]}"; do
  sudo pacman -S "$PKG" --noconfirm --needed
done

for AURPKG in "${AURPKGS[@]}"; do
  yay -S "$AURPKG" --noconfirm --needed
done

sudo mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

echo -e "\nDone!\n"
