#!/usr/bin/env bash

echo -e "\nInstalling devtools\n"

PKGS=(
  'postgresql'
  'mariadb'
  'mysql-workbench'
  'dbeaver'
)

AURPKGS=(
  'visual-studio-code-bin'
)

for PKG in "${PKGS[@]}"; do
  sudo pacman -S "$PKG" --noconfirm --needed
done

for AURPKG in "${AURPKGS[@]}"; do
  yay -Sua "$AURPKG" --noconfirm --needed
done

echo -e "\nDONE!\n"
