#!/usr/bin/env bash

echo -e "\nInstalling extras\n"

PKGS=(
  'keepassxc'
  'discord'
)

AURPKGS=(
  'heroku-cli'
  'exercism-bin'
  'etcher-bin'
  'zoom'
  'onedrive-abraunegg'
)

for PKG in "${PKGS[@]}"; do
  sudo pacman -S "$PKG" --noconfirm --needed
done

for AURPKG in "${AURPKGS[@]}"; do
  yay -S "$AURPKG" --noconfirm --needed
done

npm i -g trash-cli

echo -e "\nDone!\n"
