#!/usr/bin/env bash

echo -e "\nInstalling extras\n"

PKGS=(
  'keepassxc'
  'discord'
)

for PKG in "${PKGS[@]}"; do
  sudo pacman -S "$PKG" --noconfirm --needed
done

npm i -g trash-cli

echo -e "\nDone!\n"
