#!/usr/bin/env fish
echo -e "\nSetting KDE options...\n"

set fish_trace 1

mkdir ~/Desktop
mkdir ~/Downloads
mkdir ~/Templates
mkdir ~/Public
mkdir ~/Documents
mkdir ~/Music
mkdir ~/Pictures
mkdir ~/Videos

# titlebar buttons
kwriteconfig5 --file ~/.config/kwinrc --group org.kde.kdecoration2 --key ButtonsOnLeft MF
kwriteconfig5 --file ~/.config/kwinrc --group org.kde.kdecoration2 --key ButtonsOnRight IAX
kwriteconfig5 --file ~/.config/kwinrc --group org.kde.kdecoration2 --key CloseOnDoubleClickOnMenu false
kwriteconfig5 --file ~/.config/kwinrc --group org.kde.kdecoration2 --key ShowToolTips false

# disable borders
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key Bottom None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key BottomLeft None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key BottomRight None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key Left None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key Right None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key Top None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key TopLeft None
kwriteconfig5 --file ~/.config/kwinrc --group ElectricBorders --key TopRight None

# alt + tab
kwriteconfig5 --file ~/.config/kwinrc --group TabBox --key LayoutName big_icons
kwriteconfig5 --file ~/.config/kwinrc --group Plugins --key highlightwindowEnabled true

# do not restore desktop session
kwriteconfig5 --file ~/.config/ksmserverrc --group General --key loginMode default

# touchpad
kwriteconfig5 --file ~/.config/touchpadxlibinputrc --group "SynPS/2 Synaptics TouchPad" --key tapToClick true

# locales
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key useDetailed true
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key LANG "en_GB.UTF-8"
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key LC_COLLATE "es_PE.UTF-8"
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key LC_MEASUREMENT "es_PE.UTF-8"
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key LC_MONETARY "es_PE.UTF-8"
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key LC_NUMERIC "es_PE.UTF-8"
kwriteconfig5 --file ~/.config/plasma-localerc --group Formats --key LC_TIME "es_PE.UTF-8"

# set default applications
kwriteconfig5 --file ~/.config/kdeglobals --group General --key BrowserApplication "firefox.desktop"
kwriteconfig5 --file ~/.config/kdeglobals --group General --key TerminalApplication kitty
kwriteconfig5 --file ~/.config/kdeglobals --group General --key TerminalService "kitty.desktop"

# open files and folder with double click
kwriteconfig5 --file ~/.config/kdeglobals --group KDE --key SingleClick false

# set keyboard layout
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key DisplayNames ""
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key LayoutList us
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key Model pc86
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key ResetOldOptions false
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key ShowFlag false
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key ShowLabel true
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key ShowLayoutIndicator true
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key ShowSingle false
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key SwitchMode Global
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key Use true
kwriteconfig5 --file ~/.config/kxkbrc --group Layout --key VariantList altgr-intl

kwriteconfig5 --file ~/.config/klipperrc --group General --key IgnoreImages false
kwriteconfig5 --file ~/.config/klipperrc --group General --key KeepClipboardContents false

# night color
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key Active true
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key DayTemperature 6000
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key EveningBeginFixed 1800
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key Mode Times
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key MorningBeginFixed 0800
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key NightTemperature 3900
kwriteconfig5 --file ~/.config/kwinrc --group NightColor --key TransitionTime 45

# confirmations
kwriteconfig5 --file ~/.config/kiorc --group Confirmations --key ConfirmDelete true
kwriteconfig5 --file ~/.config/kiorc --group Confirmations --key ConfirmEmptyTrash true
kwriteconfig5 --file ~/.config/kiorc --group Confirmations --key ConfirmTrash false

set fish_trace

echo -e "\nFinished!\n"
